### ISSUE TITLE
AWS key

### ISSUE THREAD

**Issue by 0xdabbad00** [shreyasdamle/NodeProject#1]
I received an email from Amazon that you had checked in the AWS key used by my flaws.cloud project into your repo.  Please don't do that.  Please don't do use the AWS keys provided by flaws.cloud for anything other than that tutorial.  I have to roll the key now to avoid Amazon shutting flaws.cloud down.  I made flaws.cloud to help teach people, and it's free for everyone, and costs me a small amount of money to run, so please don't abuse it.  I can't tell what your project here is supposed to be, but please ensure it's not using the AWS keys associated with flaws.cloud.

**Comment by shreyasdamle** [comment]
Hi Scott,

I am extremely sorry about this. I learned a lot about AWS Security using flaws.cloud and I regularly follow your articles on Summit Route. I feel extremely foolish about my behavior.  I will never do this again. 
I was just trying to learn and I had no intensions to harm your infrastructure. Infact, I have recommended my friends/colleagues to play flaws CTF. Please let me know if I can help you in fixing this issue. Again, appologies for this.

**Comment by 0xdabbad00** [comment]
Thanks for responding.  I've rolled the key.   No further action needed.
